---
- name: Setup Terraform on New Ubuntu 22.04 System
  hosts: all
  gather_facts: true
  tasks:
    - name: Update the APT Package Cache
      become: true
      apt:
        update_cache: true
        #cache_valid_time: 3600
    - name: Before we add the Hashicorp Repo - we add the signing key
      become: true
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present
    - name: We now add the Hashicorp Repo to Ubuntu
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com jammy main"
        state: present
    - name: Install software from standard repos and hashicorp
      become: true
      apt:
        name:
          - docker.io
          - gnupg
          - software-properties-common
          - curl
          - terraform
    # - name: add userpermissions
    #   shell: "usermod -aG docker vagrant"          
    - name: We add the local USER to the Docker group
      become: true
      user:
        #name: "{{ lookup('env', 'USER') }}"
        name: vagrant
        groups: docker
        append: true
    - name: We create the directory for terraform project
      file:
        # path: "{{ lookup('env', 'HOME') }}/terraform/"
        path: "/home/vagrant/terraform/"
        state: directory
    - name: We create the web directory to store content
      file:
        path: "/home/vagrant/terraform/web"
        state: directory
    - name: Create the index page for the website
      copy:
        dest: "/home/vagrant/terraform/web/index.html"
        content: This is my web page
    # - name: We clone the course git repository
    #   git:
    #     repo: "https://github.com/wahidh007/devops-automation.git"
    #     dest: "{{ lookup('env', 'HOME') }}/devops-automation"
    #     version: main        
    # - name: We copy the main.tf terraform file from the course repo
    #   copy:
    #     src: "{{ lookup('env', 'HOME') }}/devops-automation/terraform/main.tf"
    #     dest: "{{ lookup('env', 'HOME') }}/terraform/main.tf"      
    - name: We copy the main.tf terraform file to the VM
      copy:
        src: "main.tf"
        dest: "/home/vagrant/terraform/main.tf"
    # Execute terraform init
    - name: This command will change the working directory to terraform dir/
      #become: true
      ansible.builtin.shell:
        cmd: terraform init
        chdir: "/home/vagrant/terraform/"
    # Execute terraform apply
    - name: This command will change the working directory to terraform dir/
      #become: true
      ansible.builtin.shell:
        cmd: terraform apply
        chdir: "/home/vagrant/terraform/"                
